Task/#256 add statistics details
vostpt/covid19-mobile pull request #264
Opened 2020-05-10 19:03 UTC by OldMetalmind

Closes #256 

**Description**
Adds plot regarding Confirmed Cases, Deaths, Recovered and Hospitalized information of the current status of Covid19 in Portugal. It is possible to filter by day.

**Important Note for testers**
The library used for ploting was `fl_flutter` (https://pub.dev/packages/fl_chart) and given its limitation not every feature was able to be implemented, before opening an issue please contact me @OldMetalmind .

**Not implemented**
- Logarithmic scales
- "Ticks" for the vertical lines for he x axis days
- HospitalizedUCI cases proportion not showing in between backgrounds in the plot
- Horizontal Bar plots

**Notes**
- Given the amount of new files and changes, it would be preferable to have two reviews before merging
- After this merge, we need to create more tasks for not implemented features and find a better solution for the plots and its limitations.
- There is a lot of room for improvements and code optimizations.

**Changes** 
- Added new screens for each of the types of plots details
- Navigation from the updated Statistics overview
- Loading the data from the Splash screen

2020-05-10 21:53 UTC, Vanethos commented
Can you please add screenshots? :D

2020-05-10 21:54 UTC, miguelpruivo reviewed
I have to take a whole day to review this! 😄

2020-05-10 22:13 UTC, Vanethos requested changes
Overall.. AMAZING work! Pro moves detected!!!

Only a few minor things, including a missing license and commented code

2020-05-10 22:13 UTC, Vanethos commented on lib/resources/constants.dart
> +final String dssgSourceCode = "https://github.com/dssg-pt/covid19pt-data";
can be const

2020-05-10 22:13 UTC, Vanethos commented on lib/resources/style/themes.dart
> +      headline6: TextStyles.h2(
why the change?

2020-05-10 22:13 UTC, Vanethos commented on lib/ui/screens/splash/splash_page.dart
> +      // bloc.bloc.getCovidLastUpdate();
if not in use, please remove

2020-05-10 22:13 UTC, Vanethos commented on lib/ui/screens/splash/splash_page.dart
> -    /// Get Case Stats
How can we get the home screen data if we remove this one?

2020-05-10 22:13 UTC, Vanethos commented on lib/ui/screens/statistics/components/statistics_filter.dart
> +extension StatisticsFilterExtension on StatisticsFilter {
noice! pro move!

2020-05-10 22:13 UTC, Vanethos commented on lib/ui/screens/statistics/components/statistics_new_absolute.dart
> +import 'package:covid19mobile/generated/l10n.dart';
missing header

2020-05-10 22:13 UTC, Vanethos commented on lib/ui/screens/statistics/details/confirmed_page.dart
> +    // bloc.getCovidStatus();
if not in use, we should remove

2020-05-10 22:13 UTC, Vanethos commented on lib/ui/screens/statistics/details/confirmed_page.dart
> +        /// --------------------------
Do we need this style of comment?

2020-05-10 22:13 UTC, Vanethos commented on lib/ui/screens/statistics/details/deaths_page.dart
> +    // bloc.getCovidStatus();
if not in use, we should remove

2020-05-10 22:13 UTC, Vanethos commented on lib/ui/screens/statistics/details/hospitalized_page.dart
> +          setState(() {
is this empty set state needed?

2020-05-11 10:30 UTC, miguelpruivo requested changes
Overall, like @Vanethos said, it looks great and there's an incredible amount of work here. Congrats! 🎉 

Other than minor things that I added to @Vanethos suggestions, it looks ok to me as well. I would only run `flutter format .` on the project just to make sure all files are formatted accordingly.

2020-05-11 10:30 UTC, miguelpruivo commented on lib/ui/screens/home/components/statistics_button.dart
> +        Provider.of<CovidStatusProvider>(context).statistics.confirmed;
Will this value be always available?

2020-05-11 10:30 UTC, miguelpruivo commented on lib/ui/screens/statistics/components/statistics_filter.dart
> +        .firstWhere((StatisticsFilter test, {orElse = StatisticsFilter.all}) {
I'd rather use a direct scope here, also, with Dart strings, you can use the `==` operator instead of equals for comparing both — it won't compare references only.
```
StatisticsFilter.values.firstWhere((test) => test.label(context) == str, orElse: () => StatisticsFilter.all);
```

2020-05-11 10:30 UTC, miguelpruivo commented on lib/ui/screens/statistics/components/statistics_footer.dart
> +            margin: EdgeInsets.only(bottom: 8.0, left: 8.0, right: 8.0),
Make it `const`

2020-05-11 10:30 UTC, miguelpruivo commented on lib/ui/screens/statistics/details/components/plot_types.dart
> +double calculateDividerInterval(double input) {
Where did you get this formula?

2020-05-11 13:10 UTC, OldMetalmind commented on lib/resources/style/themes.dart
> +      headline6: TextStyles.h2(
Deprecation warning by Flutter framework, it requested to update these reference to the ones I changed.

2020-05-11 13:10 UTC, OldMetalmind commented on lib/ui/screens/home/components/statistics_button.dart
> +        Provider.of<CovidStatusProvider>(context).statistics.confirmed;
Don't think I quite got the question. 
It won't be available if server is down but it will always be available over the app.

2020-05-11 13:10 UTC, OldMetalmind commented on lib/ui/screens/splash/splash_page.dart
> -    /// Get Case Stats
We get the data from the new API

2020-05-11 13:10 UTC, OldMetalmind commented on lib/ui/screens/statistics/components/statistics_filter.dart
> +        .firstWhere((StatisticsFilter test, {orElse = StatisticsFilter.all}) {
Well though, will apply your suggestion.

2020-05-11 13:10 UTC, OldMetalmind commented on lib/ui/screens/statistics/details/components/plot_types.dart
> +double calculateDividerInterval(double input) {
Late night algorithm. 
Will improve the comment to explain my train of thought.

2020-05-11 13:10 UTC, OldMetalmind commented on lib/ui/screens/statistics/details/confirmed_page.dart
> +        /// --------------------------
Will remove, was using it to keep myself organize and on track.

2020-05-11 13:10 UTC, OldMetalmind commented on lib/ui/screens/statistics/details/hospitalized_page.dart
> +          setState(() {
Will double check it.
It is to be used to update the "statistics filter" for this graph.

2020-05-11 19:21 UTC, OldMetalmind commented on lib/ui/screens/statistics/components/statistics_footer.dart
> +            margin: EdgeInsets.only(bottom: 8.0, left: 8.0, right: 8.0),
Replaced here and everywhere else it was missing.

2020-05-12 09:33 UTC, miguelpruivo approved these changes

2020-05-14 10:13 UTC, danidroid approved these changes
Amazing work @OldMetalmind 
just found some small things on UI while running on smaller devices and some imports out of place above license

2020-05-24 14:55 UTC, merged